server {
    listen 80;
    server_name localhost;
    client_max_body_size 20M;

    root /var/www/html/public;   # Указываем папку public

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";

    index index.php index.html;

    charset utf-8;

    location /storage/ {
        alias /var/www/html/storage/app/public/;
        try_files $uri =404;
    }
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Отключаем доступ к папкам с кодом
    location ~ /\.(?!well-known).* {
        deny all;
    }

    # Обработка PHP через контейнер php (имя сервиса из docker-compose)
    location ~ \.php$ {
        fastcgi_pass php:9000;
        # php - это имя сервиса в docker-compose.yml
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_read_timeout 300s;
    }

}
